data<-read.table("./household_power_consumption.txt",header=TRUE,sep=";",stringsAsFactors = FALSE, na.strings = "?")
data$Date<-as.Date(data$Date, "%d/%m/%Y")
maindata<-subset(data,data$Date=="2007-02-01"|data$Date=="2007-02-02")
maindata$datetime<-strptime(paste(maindata$Date,maindata$Time), "%Y-%m-%d %H:%M:%S")
rm(data)
png(filename = "plot4.png")
par(mfrow=c(2,2),cex=0.8)
with(maindata,plot(datetime,Global_active_power,type="n",ylab="Global Active Power",xlab=""))
lines(maindata$datetime,maindata$Global_active_power)
with(maindata,plot(datetime,Voltage,type="n",ylab="Voltage",xlab="datetime"))
lines(maindata$datetime,maindata$Voltage)
with(maindata,plot(datetime,Sub_metering_1,type="n",ylab="Energy sub metering",xlab=""))
lines(maindata$datetime,maindata$Sub_metering_1,col="black")
lines(maindata$datetime,maindata$Sub_metering_2,col="red")
lines(maindata$datetime,maindata$Sub_metering_3,col="blue")
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=1,col=c("black","red","blue"),box.col = "transparent",inset=0.01)
with(maindata,plot(datetime,Global_reactive_power,type="n"))
lines(maindata$datetime,maindata$Global_reactive_power)
dev.off()