data<-read.table("./household_power_consumption.txt",header=TRUE,sep=";",stringsAsFactors = FALSE, na.strings = "?")
data$Date<-as.Date(data$Date, "%d/%m/%Y")
maindata<-subset(data,data$Date=="2007-02-01"|data$Date=="2007-02-02")
maindata$datetime<-strptime(paste(maindata$Date,maindata$Time), "%Y-%m-%d %H:%M:%S")
rm(data)
Sys.setlocale("LC_ALL", "English")
with(maindata,plot(datetime,Global_active_power,type="n",ylab="Global Active Power(kilowatts)",xlab=""))
lines(maindata$datetime,maindata$Global_active_power)
dev.copy(png,file="plot2.png")
dev.off()