data<-read.table("./household_power_consumption.txt",header=TRUE,sep=";",stringsAsFactors = FALSE, na.strings = "?")
data$Date<-as.Date(data$Date, "%d/%m/%Y")
maindata<-subset(data,data$Date=="2007-02-01"|data$Date=="2007-02-02")
maindata$datetime<-strptime(paste(maindata$Date,maindata$Time), "%Y-%m-%d %H:%M:%S")
rm(data)
hist(maindata$Global_active_power,xlab="Global Active Power(kilowatts)",col="red", main="Global Active Power")
dev.copy(png,file="plot1.png")
dev.off()